name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的主要分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 选择合适的 Python 版本

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # 如果你使用了 Material 主题，移除此行如果不需要

      - name: Build the documentation
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # MkDocs 默认输出目录
